import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppLayout } from "@/components/layout/AppLayout";
import { getSession } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await getSession();

  return (
    <html
      lang="en"
      className={`${inter.className} bg-slate-50 min-h-screen flex flex-col antialiased`}
    >
      <body className={`${inter.className} antialiased text-slate-800`}>
        {session ? (
          <AppLayout user={session}>{children}</AppLayout>
        ) : (
          <main className="min-h-screen bg-slate-50">{children}</main>
        )}
      </body>
    </html>
  );
}
